# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Android build 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_for_android:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Download Artifact
          uses: actions/download-artifact@master
          with:
            name: release-apk
        - name: Upload APK
          uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
          with:
            appId: ${{secrets.FIREBASE_ANDROID_APPID}}
            token: ${{secrets.FIREBASE_TOKEN}}
            group: testers
            file: app-release.apk
